generator:
    develop: True
    down: False
    residual: True
    in_channels: 3
    dropfirst_encoders: 0
    dropsecond_encoders: 0.5
    normalize_encoder: 0
    activation_encoder: 0
    padingtype_encoder: 1
    shuffle: False
    out_channels: 3
    dropfirst_decoder: 0
    dropsecond_decoder: 0.5
    normalize_decoder: 0
    activation_decoder: 0
    padingtype_decoder: 1

discriminator:
    channels: 6
    classes: 1
    develop: True
    residual: True
    down: False
    activation: 0
    normalize: 0
    dropfirst: 0
    dropsecond: 0.5
    padingtype: 1

data:
    dataset: ./generate/'
    channels: 3
    develop: True

develop: True
temp_log_dir: './logs'
batch_size: 16
interval_save: 40
display_step: 10
lambda_recon: 200
noise_decrease: 0.01
lrg: 0.0002
b1g: 0.9
b2g: 0.999
lrc: 0.0002
b1c: 0.9
b2c: 0.999